exp:
  dir: logs/vqa2/iter2_fixed_no_c
  resume: last
dataset:
  import: murel.datasets.factory
  name: vqa2
  dir: data/vqa/vqa2
  train_split: train
  eval_split: val
  proc_split: train
  nb_threads: 8
  batch_size: 20
  nans: 3000
  minwcount: 0
  nlp: mcb
  samplingans: true
  dir_rcnn: data/vqa/coco/extract_rcnn/2018-04-27_bottom-up-attention_fixed_36
  vg: false
  dir_vg: data/vqa/vgenome
  dir_rcnn_vg: data/vqa/vgenome/extract_rcnn/2018-04-27_bottom-up-attention_fixed_36
model:
  name: default
  network:
    import: murel.models.networks.factory
    name: itereg_net
    txt_enc:
      name: skipthoughts
      type: BayesianUniSkip
      dropout: 0.25
      fixed_emb: True
      dir_st: data/skip-thoughts
    self_q_att: True
    n_step: 2
    shared: true
    cell:
      residual: true
      fusion:
        type: block
        input_dims:
        - 4800
        - 2048
        output_dim: 2048
        mm_dim: 1000
        chunks: 20
        rank: 15
        dropout_input: 0.1
        dropout_pre_lin: 0.0
      control:
        input_size: 4800
        hidden_size: 512
      graph:
        in_feature_dim: 2048
        combined_feature_dim: 720
        K: 36
        dropout: 1
      relations:
        residual: true
        fusion_coord:
          type: block
          input_dims:
          - 4
          - 4
          output_dim: 2048
          mm_dim: 200
          chunks: 5
          rank: 5
          dropout_input: 0.0
          dropout_pre_lin: 0.0
        fusion_feat:
          type: block
          input_dims:
          - 2048
          - 2048
          output_dim: 2048
          mm_dim: 200
          chunks: 5
          rank: 5
          dropout_input: 0.0
          dropout_pre_lin: 0.0
        agg:
          type: max
    agg:
      type: max
    classif:
      fusion:
        type: block
        input_dims:
        - 4800
        - 2048
        output_dim: 3000
        mm_dim: 1600
        chunks: 20
        rank: 10
        dropout_input: 0.1
        dropout_pre_lin: 0.0
  criterion:
    import: murel.models.criterions.factory
    name: vqa_cross_entropy
  metric:
    import: murel.models.metrics.factory
    name: vqa_accuracies
optimizer:
  import: murel.optimizers.factory
  name: Adam
  lr: 0.0002
  gradual_warmup_steps:
  - 0.5
  - 2.0
  - 7.0
  lr_decay_epochs:
  - 14
  - 24
  - 2
  lr_decay_rate: 0.25
engine:
  name: logger
  debug: false
  print_freq: 10
  nb_epochs: 25
  saving_criteria:
  - eval_epoch.accuracy_top1:max
misc:
  logs_name: null
  cuda: true
  seed: 1337
view:
  name: plotly
  items:
  - logs:train_epoch.loss+logs:eval_epoch.loss
  - logs:train_epoch.accuracy_top1+logs:eval_epoch.accuracy_top1
  - logs_train_oe:train_epoch.overall+logs_val_oe:eval_epoch.overall